apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    nebula-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      {{- if .Values.server.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.server.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: server
        nebula-version: {{ .Chart.AppVersion }}
        {{- if .Values.server.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.server.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.server.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      serviceAccountName: {{ template "server.serviceAccountName" . }}
      {{- if .Values.server.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.server.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.server.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.server.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.podSecurityContext }}
      securityContext: {{- .Values.server.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.server.priorityClassName }}
      priorityClassName: {{ .Values.server.priorityClassName }}
      {{- end }}
      containers:
        - name: nebula-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.nebulaTag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - /usr/bin/tini
            - -g
            - --
            - /opt/nebula/entrypoint.sh
          args:
            - nebula
            - server
            - start
            - --port
            - {{ .Values.service.targetPort | quote }}
            {{- range .Values.server.extraArgs }}
            - {{ . | toString }}
            {{- end }}
          workingDir: /home/nebula
          ports:
            - containerPort: {{ int .Values.service.targetPort }}
          env:
            - name: HOME
              value: /home/nebula
            - name: NEBULA_API_URL
              value: {{ .Values.server.nebulaApiUrl | quote }}
            - name: NEBULA_DEBUG_MODE
              value: {{ .Values.server.debug | quote }}
            - name: NEBULA_LOGGING_SERVER_LEVEL
              value: {{ .Values.server.loggingLevel | quote }}
            - name: NEBULA_SERVER_API_HOST
              value: {{ .Values.server.nebulaApiHost | quote }}
            - name: NEBULA_SERVER_API_PORT
              value: {{ .Values.service.targetPort  | quote }}
            - name: NEBULA_UI_ENABLED
              value: {{ .Values.server.uiConfig.enabled | quote }}
            {{- if .Values.server.uiConfig.nebulaUiApiUrl }}
            - name: NEBULA_UI_API_URL
              value: {{ .Values.server.uiConfig.nebulaUiApiUrl | quote }}
            {{- end }}
            {{- if .Values.server.uiConfig.nebulaUiUrl }}
            - name: NEBULA_UI_URL
              value: {{ .Values.server.uiConfig.nebulaUiUrl | quote }}
            {{- end }}
            - name: NEBULA_UI_STATIC_DIRECTORY
              value: {{ .Values.server.uiConfig.nebulaUiStaticDirectory | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: NEBULA_API_DATABASE_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.postgres-string-secret-name" . }}
                  key: connection-string
            {{- end }}
            {{- if .Values.server.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.server.env "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.server.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.server.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.server.resources }}
          resources: {{- toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.server.containerSecurityContext }}
          securityContext: {{- .Values.server.containerSecurityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
          {{- toYaml .Values.server.livenessProbe.config | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /api/ready
              port: {{ .Values.service.targetPort }}
          {{- toYaml .Values.server.readinessProbe.config | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /home/nebula
              name: scratch
              subPathExpr: home
            - mountPath: /tmp
              name: scratch
              subPathExpr: tmp
            - mountPath: {{ .Values.server.uiConfig.nebulaUiStaticDirectory }}
              name: scratch
              subPathExpr: ui-build
          {{- if .Values.server.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.server.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.server.extraContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.extraContainers "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: scratch
          emptyDir: {}
        {{- if .Values.server.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
