apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-nebula-exporter.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "prometheus-nebula-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-nebula-exporter.selectorLabels" . | nindent 4 }}
