{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-nebula-exporter.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "prometheus-nebula-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
