name: Lint and Test Prometheus Nebula Exporter Chart

"on":
  pull_request:

jobs:
  lint_test:
    name: "lint-test (${{ matrix.kubernetes }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - "1.26.0"
          - "1.27.0"
          - "1.28.0"
          - "1.29.0"
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/prometheus-nebula-exporter-ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          node_image: "kindest/node:v${{ matrix.kubernetes }}"

      - name: Install Nebula Server
        run: |
          helm dependency build ./charts/nebula-server/
          helm install nebula-server -n default ./charts/nebula-server/ --set=postgresql.auth.password=TESTING

      - name: Run chart-testing (install)
        run: |
          ct install --config .github/linters/prometheus-nebula-exporter-ct.yaml --helm-extra-set-args "--set=nebulaApiUrl=http://nebula-server.default.svc.cluster.local:4200/api"
